apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job-9012-20037-29749
  namespace: jobs
spec:
  template:
    spec:
      containers:
      - name: batch-job-9012-20037-29749
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(200)"]
      restartPolicy: Never
  backoffLimit: 1
