apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job-6714-3598-14976
  namespace: jobs
spec:
  template:
    spec:
      containers:
      - name: batch-job-6714-3598-RAND3
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(200)"]
      restartPolicy: Never
  backoffLimit: 1
