apiVersion: batch/v1
kind: Job
metadata:
  name: serverless-3
  namespace: jobs
spec:
  template:
    spec:
      containers:
      - name: serverless-3
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(200)"]
      restartPolicy: Never
  backoffLimit: 1